SELECT CONCAT(O.NAME, '(', LEFT(O.OCCUPATION, 1), ')') AS CON 
FROM OCCUPATIONS O 
ORDER BY O.NAME;

SELECT CONCAT('There are a total of ', COUNT(O.OCCUPATION), ' ', LOWER(O.OCCUPATION), 's.') as STRI 
FROM OCCUPATIONS O
GROUP BY O.OCCUPATION 
ORDER BY COUNT(O.OCCUPATION);